{
  "sanic_1": {
    "status": "running",
    "time": {
      "checkout": 0.13234853744506836,
      "instrument": 30.010234594345093,
      "test": 28.77407145500183
    },
    "checkout": "successful",
    "build": "successful",
    "test": "successful",
    "check": "successful"
  },
  "sanic_2": {
    "status": "skipped"
  },
  "sanic_3": {
    "status": "running",
    "time": {
      "checkout": 0.17405128479003906,
      "instrument": 34.5890429019928,
      "test": 20.044615268707275
    },
    "checkout": "successful",
    "build": "successful",
    "test": "successful",
    "check": "successful"
  },
  "sanic_4": {
    "status": "running",
    "time": {
      "checkout": 0.17856311798095703,
      "instrument": 33.0892698764801
    },
    "checkout": "successful",
    "build": "failed",
    "error": [
      "Traceback (most recent call last):\n",
      "  File \"/home/smytzek/efdd/study/venv/lib/python3.11/site-packages/tests4py/sfl/__init__.py\", line 42, in sflkit_instrument\n    instrument(\n",
      "  File \"/home/smytzek/efdd/study/venv/lib/python3.11/site-packages/tests4py/sfl/utils.py\", line 120, in instrument\n    raise report.raised\n",
      "  File \"/home/smytzek/efdd/study/venv/lib/python3.11/site-packages/tests4py/api/default.py\", line 363, in build\n    subprocess.check_call(\n",
      "  File \"/home/smytzek/.pyenv/versions/3.11.4/lib/python3.11/subprocess.py\", line 413, in check_call\n    raise CalledProcessError(retcode, cmd)\n",
      "subprocess.CalledProcessError: Command '['python', '-m', 'pip', 'install', '-e', '.']' returned non-zero exit status 1.\n"
    ]
  },
  "sanic_5": {
    "status": "running",
    "time": {
      "checkout": 0.13345026969909668,
      "instrument": 42.0108482837677,
      "test": 5.401112079620361
    },
    "checkout": "successful",
    "build": "successful",
    "test": "successful",
    "check": "successful"
  }
}